### ISSUE TITLE
blade.actioncommand / freemarker broken

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#249]
After the latest update, freemarker rendering doesn't seem to work anymore. The portlet works, and but when added to a page, it renders an empty portlet with no content, rather than rendering freemarker content. (Tested on a freshly built server from master).

**Comment by deadcyclo** [comment]
Just discovered that all of the freemarker-related bundles are marked as Resolved rather than active when starting the portal. So I guess the issue probably isn't a blade issue. Anybody know if this is a known issue?

**Comment by deadcyclo** [comment]
13:23:19,737 ERROR [Framework Event Dispatcher: Equinox Container: c0fc1140-c3e6-0015-1254-b70883dfc7d1][com_liferay_util_taglib:96] FrameworkEvent ERROR 
org.osgi.framework.BundleException: Could not resolve module: com.liferay.util.taglib [484]_  Unresolved requirement: Import-Package: javax.el_ [Sanitized]
        at org.eclipse.osgi.container.Module.start(Module.java:429)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:566)
        at org.eclipse.osgi.container.Module.start(Module.java:434)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:390)
        at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
        at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:256)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by deadcyclo** [comment]
Created an issue: https://issues.liferay.com/browse/LPS-64110

**Comment by deadcyclo** [comment]
After updating to the latest kernel and utils version, the portlet is now not finding the freemarker files.

11:32:47,341 ERROR [http-nio-8080-exec-5][FreeMarkerPortlet:78] /view.ftl is not a valid include

(I'll try to investigate, but your input would be appreciated @rotty3000 )

**Comment by deadcyclo** [comment]
Sort of works now in pr  #254 (but path always root, this is an issue with the FreemarkerPortlet implementatio.

**Comment by rotty3000** [comment]
was an issue ever created for the freemarker portlet not finding files?

**Comment by deadcyclo** [comment]
No. I don't think anything was created other than the one you closed.
